services:
  # 개발 환경용 - 백엔드와 프론트엔드를 하나의 컨테이너로 통합
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"  # Frontend
      - "8000:8000"  # Backend API
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
      - DATABASE_URL=sqlite:///./data/app.db
      - KEPCO_API_KEY=${KEPCO_API_KEY:-sample_key}
      - WEATHER_API_KEY=${WEATHER_API_KEY:-sample_key}
    volumes:
      - .:/workspace
      - /workspace/node_modules
      - /workspace/frontend/node_modules
      - /workspace/backend/__pycache__
    working_dir: /workspace
    command: >
      sh -c "
        echo 'Starting AI Datacenter Power Analyzer...' &&
        cd /workspace/backend && python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload &
        cd /workspace/frontend && npm run dev -- --host 0.0.0.0 --port 3000 &
        wait
      "